### ISSUE TITLE
add profiles to lone code recipe

### ISSUE THREAD

**Issue by NickleDave** [ResearchCodeReviewCommunity/dev-review#1]
thinking of something like this, "learner profiles", at the top of either the flowchart or the more detailed walkthrough we have now

https://software-carpentry.org/audience/

could have for both author and reviewer

**Comment by tlestang** [comment]
Oh that's a good idea. This could help a lot with inclusivity, particularly in convincing people they can be reviewers too

**Comment by NickleDave** [comment]
Closing, we have added profiles at bottom of pages now
