### ISSUE TITLE
Complete the second (right) half of the single developer flowchart

### ISSUE THREAD

**Issue by bielsnohr** [ResearchCodeReviewCommunity/dev-review#25]
To be implemented in Mermaid. Half finished flowchart source is at `site/content/flowcharts/lonecoder.md`. Lucid chart for what it should look like: https://lucid.app/lucidchart/5c8489cf-fb36-4563-b44b-6cb1fff8125a/view?page=0_0#

**Comment by NickleDave** [comment]
I'm attaching the Lucid chart as an image so I don't have to click / for ppl that don't have access
![Screen Shot 2021-08-31 at 4 01 53 PM](https://user-images.githubusercontent.com/11934090/131569892-add831bf-90ef-46ab-ac7b-dbffcb9e232a.png)
