### ISSUE TITLE
for references: blog post from osc-delft

### ISSUE THREAD

**Issue by NickleDave** [ResearchCodeReviewCommunity/dev-review#27]
https://osc-delft.github.io/posts/2021/09/03/Research-Code-Review/

**Comment by NickleDave** [comment]
it just dawned on me this is the the event that @bielsnohr recommended to us
whoops 😬 

key points that @mxochicale pointed out in email

> It might be more but I like these two key messages:
> * "Try to make the bar as low as possible for code review ... does this code exist & work?" StephenEglen
> * something can be learn from these communities CODECHECK, Reprohack and the Turing Way)

**Comment by mxochicale** [comment]
Hi @NickleDave , @bielsnohr  and all

What I can do is to review and summarise what these three communities are doing [CODECHECK](https://codecheck.org.uk/) [:octocat:](https://github.com/codecheckers/), [Reprohack](https://reprohack.github.io/reprohack-hq/) [:octocat:](https://github.com/reprohack) and [the Turing Way](https://the-turing-way.netlify.app/welcome.html) [:octocat:](https://github.com/alan-turing-institute/the-turing-way). Another community that might be considered is http://rescience.github.io/ [:octocat:](https://github.com/rescience/) Let me just brainstorm few ideas that can be considered in the summary:
* When it was created?
* What's the main aim purpose of each community? 
* How many members and how active is the community in terms of submissions per month? 
* What is the model/workflow/pipeline for code review? 
* ...any other?

The above might be helpful to have some sort of state-of-the-art of code review communities.
