### ISSUE TITLE
Explicit installing instructions?

### ISSUE THREAD

**Issue by mxochicale** [ResearchCodeReviewCommunity/dev-review#32]
I am trying to install `hugo extended` in Ubuntu 20.04x64 using https://gohugo.io/getting-started/installing but it is not a straightforward process, perhaps I will try to add few instructions for those GNU/Linux users who want to have a go to the website.

**Comment by fcooper8472** [comment]
I would suggest using snap:
```
snap install hugo --channel=extended
```

**Comment by NickleDave** [comment]
I'm on an Ubuntu-like system and I just use `brew` -- gets me the latest version and it's automatically "extended"

might be worth mentioning that alternative, esp since the Hugo docs seem to be in favor of it over system package managers

https://gohugo.io/getting-started/installing/#debian-and-ubuntu

(although yes they recommend `snap` right above that)

**Comment by mxochicale** [comment]
As expected the instlalation was not very smoothly in Ubuntu, see few logs on trying to install hugo extenteded : 

* snap 
```
$ sudo snap install hugo --channel=extended
$ hugo serve --disableFastRender
bash: /usr/bin/hugo: No such file or directory

$ whereis hugo
hugo: /snap/bin/hugo


$ ls -l /snap/bin/hugo

$ hugo serve --disableFastRender
Start building sites … 
hugo v0.88.1+extended linux/amd64 BuildDate=2021-09-04T13:52:13Z
Error: Error building site: "/home/mx19/xfiles/dev-review/site/content/_index.md:3:1": failed to extract shortcode: template for shortcode "mermaid" not found
Built in 1 ms

$ sudo snap remove hugo 
$ rm -rf /snap/hugo
```
[:link:](https://gohugo.io/getting-started/installing/#snap-package)


* apt-get 
```
$ sudo apt-get install hugo

hugo serve
Built in 1 ms
Error: Error building site: "/home/mx19/xfiles/dev-review/site/content/_index.md:3:1": failed to extract shortcode: template for shortcode "mermaid" not found

sudo apt-get remove --purge hugo
```
which clearly is not update [[:link:](https://gohugo.io/getting-started/installing/#debian-and-ubuntu)]


* brew
```
$sudo apt-get install build-essential procps curl file git
$ cd
$ sudo mkdir linuxbrew

$ git clone https://github.com/Homebrew/brew ~/.linuxbrew/Homebrew
$ mkdir ~/.linuxbrew/bin
$ ln -s ~/.linuxbrew/Homebrew/bin/brew ~/.linuxbrew/bin
$ eval "$(~/.linuxbrew/bin/brew shellenv)"


$ brew install hugo
```
[:link: ](https://docs.brew.sh/Homebrew-on-Linux)

:heart:  `==> Homebrew is run entirely by unpaid volunteers. Please consider donating:`


```
 hugo serve
Start building sites … 
hugo v0.88.1+extended linux/amd64 BuildDate=unknown
Error: Error building site: "/home/mx19/xfiles/dev-review/site/content/_index.md:3:1": failed to extract shortcode: template for shortcode "mermaid" not found
Built in 1 ms

```

from the brew installation see more info:

```
**$ brew info hugo 
hugo: stable 0.88.1 (bottled), HEAD
Configurable static site generator
https://gohugo.io/
/home/mx19/.linuxbrew/Cellar/hugo/0.88.1 (47 files, 48.6MB) *
  Poured from bottle on 2021-09-24 at 18:19:46
From: https://github.com/Homebrew/linuxbrew-core/blob/HEAD/Formula/hugo.rb
License: Apache-2.0
==> Dependencies
Build: go ✘
==> Options
--HEAD
	Install HEAD version
==> Caveats
Bash completion has been installed to:
  /home/mx19/.linuxbrew/etc/bash_completion.d
==> Analytics
install: 1,171 (30 days), 3,339 (90 days), 12,342 (365 days)
install-on-request: 1,175 (30 days), 3,346 (90 days), 12,355 (365 days)
build-error: 0 (30 days)
**
```

```
 brew remove  hugo
Uninstalling /home/mx19/.linuxbrew/Cellar/hugo/0.88.1... (47 files, 48.6MB)
```



* git/go
```
mkdir $HOME/src
cd $HOME/src
git clone https://github.com/gohugoio/hugo.git
cd hugo

sudo apt-get install golang
sudo apt-get remove golang
sudo apt-get remove golang-go
sudo apt-get remove --auto-remove golang-go
>You need go v1.16+ 

sudo su
rm -rf /usr/local/go && tar -C /usr/local -xzf go1.17.1.linux-amd64.tar.gz 
exit

echo 'export PATH=$PATH:/usr/local/go/bin' >> ~/.bashrc 
source ~/.bashrc 
go version
>go version go1.17.1 linux/amd64 #REF https://golang.org/doc/install 

cd $HOME/src/hugo
go install --tags extended

```
:tada:  no errors `~/src/hugo$ go install --tags extended` but now don't know how to call hugo

**Comment by fcooper8472** [comment]
Ah - the error that you're getting:
```
Error: Error building site: "/home/mx19/xfiles/dev-review/site/content/_index.md:3:1": failed to extract shortcode: template for shortcode "mermaid" not found
```

to me indicates the problem is likely NOT be with Hugo itself.
Hugo allows you to use templates, and I have used the [Loveit](https://hugoloveit.com/) theme, which is distributed as a submodule.

If I'm right, you should just need to clone the repository following these instructions in the README (the important part is the `--recurse-submodules`):
https://github.com/ResearchCodeReviewCommunity/dev-review#previewing-changes-locally

I would recommend cloning the repository with the submodule, and then try with hugo installed via snap.
Let me know how you get on!

**Comment by NickleDave** [comment]
I ran into this again this AM, although by now I know how to translate the error into --> "I forgot to update the submodules"

I wonder if 
* we should add some troubleshoot section to the README that includes this error
* add a small shell script that just does all the setup steps?
