### ISSUE TITLE
Add a step to review the overall context of the code

### ISSUE THREAD

**Issue by bielsnohr** [ResearchCodeReviewCommunity/dev-review#45]
During our meeting about outlining the actual code review cycle (notes [here](https://hackmd.io/MIIR05s6T1CCOS0JohpnLg?both#Code-author-communicates-code-and-context), it was agreed that the _overall_ structure and context of the code should be explained at the "Meet and Agree on Objectives" step. Looking at our current recipe for that step, explicit mention of the author introducing the code, its purpose, and structure is missing: https://github.com/ResearchCodeReviewCommunity/dev-review/blob/main/site/content/recipes/meet_and_agree_on_objectives.md

**Comment by NickleDave** [comment]
I think this was fixed by #65 even though as discussion there states the "explain code structure" might not be completely integrated

I'm going to close this issue since I think it duplicates others (#61)
