### ISSUE TITLE
revise index to make clearer the focus on 1-on-1 research review for newbies

### ISSUE THREAD

**Issue by NickleDave** [ResearchCodeReviewCommunity/dev-review#52]
i.e., in contrast with established review methods for large tech teams in industry

**Comment by tlestang** [comment]
> We provide a lightweight process targeted to researchers writing analysis code and smaller tools, that could benefit from code review but do not have an established team to work with.


> ...and then explain that the goal of the site to present a lightweight process meant for researchers working alone or in small groups that provides the same benefits as code review as it is done by RSE teams and in industry

Both are great and should definitely be on the welcome page, but I don't see them in #52 ?

**Comment by NickleDave** [comment]
Coming back to this

> rename to something like "code review for researchers" or "code review for scientists"; in my mind what we have now builds directly on the Petre + Wilson paper "code review by and for scientists"

I think we should explicitly link Petre Wilson 2015, say something like "what we present is inspired in large part by what's described here, little work has been done since that time on code review for researchers that do not consider themselves software engineers"
